[theme]

# Primary accent for interactive elements
primaryColor = '#DC5F00'

# Background color for the main content area
backgroundColor = '#EEEEEE'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#686D76'

# Color used for almost all text
textColor = '#202020'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"